name: axe
on:
  pull_request:
    branches: [main]
env:
  BUILD_DIR: 'client/www/next-build'
jobs:
  axe:
    name: Runs axe accessibility testing on changed pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2 https://github.com/actions/checkout/commit/9bb56186c3b09b4f86b1c65136769dd318469633
        with: 
          ref: main
      - name: Setup Node.js 20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # 4.0.2 https://github.com/actions/setup-node/releases/tag/v4.0.2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Run site
        run: | 
          python -m http.server 3000 -d ${{ env.BUILD_DIR }} &
          sleep 5
      - name: Run axe cli
        run: | 
          npm install -g  @axe-core/cli
          axe http://localhost:3000/react/how-amplify-works/ --exit

