name: Test
on:
  pull_request:
    branches: [main, next-release/main]
    types: [opened, synchronize]
env:
  BUILD_DIR: 'client/www/next-build'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0 https://github.com/actions/checkout/commit/f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Setup Node.js 20.x
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v.3.8.1 https://github.com/actions/setup-node/commit/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run tests
        run: yarn prebuild && yarn test
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Run site
        run: | 
          python -m http.server 3000 -d ${{ env.BUILD_DIR }} &
          sleep 5
      - name: Run tests
        run: yarn test:e2e
